### ISSUE TITLE
loss error

### ISSUE THREAD

**Issue by ats4869** [Coral79/CDDB#3]
Traceback (most recent call last):
  File "main.py", line 572, in <module>
    main(args)
  File "main.py", line 308, in main
    train_stats = train_one_epoch(
  File "/mnt/data/zhangyufei/deepfake/CDDB/CDDB-main/DyTox/continual/engine.py", line 78, in train_one_epoch
    check_loss(loss)
  File "/mnt/data/zhangyufei/deepfake/CDDB/CDDB-main/DyTox/continual/engine.py", line 161, in check_loss
    raise Exception('Loss is {}, stopping training'.format(loss.item()))
Exception: Loss is nan, stopping training

**Comment by ats4869** [comment]
run DyTox error
